#pragma once

#include "dlna/common/DLNADescr.h"
#include "dlna/xml/XMLPrinter.h"

namespace tiny_dlna {

/**
 * @brief AVTransport service descriptor (SCPD) generator
 *
 * This class implements the DLNA AVTransport service description printer.
 * It produces the service SCPD XML by writing into any Arduino-style
 * Print implementation.
 * The primary method is printDescr(Print& out) which emits the XML and
 * returns the number of bytes written. The implementation is stateless and
 * safe to construct on-demand where needed.
 */

class DLNAMediaRendererTransportDescr : public DLNADescr {
 public:
  size_t printDescr(Print& out) override {
    const char* txt =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
        "  <specVersion>\n"
        "    <major>1</major>\n"
        "    <minor>0</minor>\n"
        "  </specVersion>\n"
        "  <actionList>\n"
        "    <!-- Essential Actions -->\n"
        "    <action>\n"
        "      <name>SetAVTransportURI</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentURI</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>AVTransportURI</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentURIMetaData</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>Play</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Speed</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>TransportPlaySpeed</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>Stop</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>Pause</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <!-- Recommended Query Actions -->\n"
        "    <action>\n"
        "      <name>GetTransportInfo</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentTransportState</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>TransportState</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentTransportStatus</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>TransportStatus</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentSpeed</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>TransportPlaySpeed</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>GetPositionInfo</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Track</name>\n"
        "          <direction>out</direction>\n"
        "          <relatedStateVariable>CurrentTrack</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>TrackDuration</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>CurrentTrackDuration</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>TrackMetaData</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>CurrentTrackMetaData</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>TrackURI</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>CurrentTrackURI</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>RelTime</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>RelativeTimePosition</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>AbsTime</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>AbsoluteTimePosition</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>RelCount</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>RelativeCounterPosition</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>AbsCount</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>GetMediaInfo</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>NrTracks</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>NumberOfTracks</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>MediaDuration</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>CurrentMediaDuration</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentURI</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>AVTransportURI</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentURIMetaData</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>NextURI</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>NextAVTransportURI</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>NextURIMetaData</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>NextAVTransportURIMetaData</"
        "relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>PlayMedium</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>PlaybackStorageMedium</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>RecordMedium</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>RecordStorageMedium</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>WriteStatus</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>RecordMediumWriteStatus</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "  </actionList>\n"
        "\n"
        "  <serviceStateTable>\n"
        "    <!-- Essential State Variables -->\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>TransportState</name>\n"
        "      <dataType>string</dataType>\n"
        "      <allowedValueList>\n"
        "        <allowedValue>STOPPED</allowedValue>\n"
        "        <allowedValue>PLAYING</allowedValue>\n"
        "        <allowedValue>PAUSED_PLAYBACK</allowedValue>\n"
        "        <allowedValue>TRANSITIONING</allowedValue>\n"
        "        <allowedValue>NO_MEDIA_PRESENT</allowedValue>\n"
        "      </allowedValueList>\n"
        "      <defaultValue>NO_MEDIA_PRESENT</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>TransportStatus</name>\n"
        "      <dataType>string</dataType>\n"
        "      <allowedValueList>\n"
        "        <allowedValue>OK</allowedValue>\n"
        "        <allowedValue>ERROR_OCCURRED</allowedValue>\n"
        "      </allowedValueList>\n"
        "      <defaultValue>OK</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>TransportPlaySpeed</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue>1</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <!-- Media-related State Variables -->\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>AVTransportURI</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>AVTransportURIMetaData</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>CurrentTrack</name>\n"
        "      <dataType>ui4</dataType>\n"
        "      <defaultValue>0</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>CurrentTrackDuration</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>RelativeTimePosition</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>AbsoluteTimePosition</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <!-- Argument Type State Variables -->\n"
        "    <stateVariable sendEvents=\"no\">\n"
        "      <name>A_ARG_TYPE_InstanceID</name>\n"
        "      <dataType>ui4</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <!-- Additional required state variables (can have empty/default "
        "values) -->\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>CurrentTrackMetaData</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>CurrentTrackURI</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>RelativeCounterPosition</name>\n"
        "      <dataType>i4</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>AbsoluteCounterPosition</name>\n"
        "      <dataType>i4</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>NumberOfTracks</name>\n"
        "      <dataType>ui4</dataType>\n"
        "      <defaultValue>0</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>CurrentMediaDuration</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>NextAVTransportURI</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>NextAVTransportURIMetaData</name>\n"
        "      <dataType>string</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>PlaybackStorageMedium</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue>NETWORK</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>RecordStorageMedium</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue>NOT_IMPLEMENTED</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>RecordMediumWriteStatus</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue>NOT_IMPLEMENTED</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "  </serviceStateTable>\n"
        "</scpd>\n"
        "";
    return out.print(txt);
  }
};

/**
 * @brief RenderingControl service descriptor (SCPD) generator
 *
 * This class implements the DLNA RenderingControl service description.
 * Use printDescr(Print& out) to emit the SCPD XML to any Print-backed
 * output. The method returns the number of bytes written so callers can
 * measure content-length when streaming HTTP responses without buffering.
 * The class does not keep runtime state and may be constructed per-call.
 */
class DLNAMediaRendererControlDescr : public DLNADescr {
 public:
  size_t printDescr(Print& out) override {
    const char* txt =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
        "  <specVersion>\n"
        "    <major>1</major>\n"
        "    <minor>0</minor>\n"
        "  </specVersion>\n"
        "  <actionList>\n"
        "    <!-- Essential Volume Control -->\n"
        "    <action>\n"
        "      <name>SetVolume</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Channel</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>DesiredVolume</name>\n"
        "          <direction>in</direction>\n"
        "          <relatedStateVariable>Volume</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>GetVolume</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Channel</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentVolume</name>\n"
        "          <direction>out</direction>\n"
        "          <relatedStateVariable>Volume</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <!-- Essential Mute Control -->\n"
        "    <action>\n"
        "      <name>SetMute</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Channel</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>DesiredMute</name>\n"
        "          <direction>in</direction>\n"
        "          <relatedStateVariable>Mute</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <action>\n"
        "      <name>GetMute</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Channel</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentMute</name>\n"
        "          <direction>out</direction>\n"
        "          <relatedStateVariable>Mute</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "    <!-- Optional but recommended -->\n"
        "    <action>\n"
        "      <name>ListPresets</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>InstanceID</name>\n"
        "          <direction>in</direction>\n"
        "          "
        "<relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>CurrentPresetNameList</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>PresetNameList</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "\n"
        "  </actionList>\n"
        "\n"
        "  <serviceStateTable>\n"
        "    <!-- Core State Variables -->\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>Volume</name>\n"
        "      <dataType>ui2</dataType>\n"
        "      <allowedValueRange>\n"
        "        <minimum>0</minimum>\n"
        "        <maximum>100</maximum>\n"
        "        <step>1</step>\n"
        "      </allowedValueRange>\n"
        "      <defaultValue>50</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>Mute</name>\n"
        "      <dataType>boolean</dataType>\n"
        "      <defaultValue>0</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <!-- Argument Type State Variables -->\n"
        "    <stateVariable sendEvents=\"no\">\n"
        "      <name>A_ARG_TYPE_InstanceID</name>\n"
        "      <dataType>ui4</dataType>\n"
        "    </stateVariable>\n"
        "\n"
        "    <stateVariable sendEvents=\"no\">\n"
        "      <name>A_ARG_TYPE_Channel</name>\n"
        "      <dataType>string</dataType>\n"
        "      <allowedValueList>\n"
        "        <allowedValue>Master</allowedValue>\n"
        "      </allowedValueList>\n"
        "    </stateVariable>\n"
        "\n"
        "    <!-- Preset Support -->\n"
        "    <stateVariable sendEvents=\"no\">\n"
        "      <name>PresetNameList</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue>FactoryDefault</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "    <!-- Additional variables (minimal set) -->\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>Brightness</name>\n"
        "      <dataType>ui2</dataType>\n"
        "      <allowedValueRange>\n"
        "        <minimum>0</minimum>\n"
        "        <maximum>100</maximum>\n"
        "        <step>1</step>\n"
        "      </allowedValueRange>\n"
        "      <defaultValue>50</defaultValue>\n"
        "    </stateVariable>\n"
        "\n"
        "  </serviceStateTable>\n"
        "</scpd>\n"
        "";
    return out.print(txt);
  }
};

/**
 * @brief ConnectionManager service descriptor (SCPD) generator
 *
 * Produces the ConnectionManager SCPD XML via printDescr(Print& out).
 * The returned size_t value equals the number of bytes written. The
 * implementation follows the same stateless pattern as the other
 * descriptor classes and is intended to be used when responding to
 * service description requests (service.xml).
 */
class DLNAMediaRendererConnectionMgrDescr : public DLNADescr {
 public:
  size_t printDescr(Print& out) override {
    const char* msg =
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
        "  <specVersion>\n"
        "    <major>1</major>\n"
        "    <minor>0</minor>\n"
        "  </specVersion>\n"
        "  <actionList>\n"
        "    <action>\n"
        "      <name>GetProtocolInfo</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>Source</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>SourceProtocolInfo</relatedStateVariable>\n"
        "        </argument>\n"
        "        <argument>\n"
        "          <name>Sink</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>SinkProtocolInfo</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "    <action>\n"
        "      <name>GetCurrentConnectionIDs</name>\n"
        "      <argumentList>\n"
        "        <argument>\n"
        "          <name>ConnectionIDs</name>\n"
        "          <direction>out</direction>\n"
        "          "
        "<relatedStateVariable>CurrentConnectionIDs</relatedStateVariable>\n"
        "        </argument>\n"
        "      </argumentList>\n"
        "    </action>\n"
        "    <!-- Optional: Remove PrepareForConnection and "
        "GetCurrentConnectionInfo for simpler implementation -->\n"
        "  </actionList>\n"
        "  <serviceStateTable>\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>SourceProtocolInfo</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue></defaultValue>\n"
        "    </stateVariable>\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>SinkProtocolInfo</name>\n"
        "      <dataType>string</dataType>\n"
        "      <!-- Example: Add supported formats -->\n"
        "      "
        "<defaultValue>http-get:*:audio/mpeg:*,http-get:*:audio/"
        "wav:*,http-get:*:audio/L16:*,http-get:*:audio/flac:*</defaultValue>\n"
        "    </stateVariable>\n"
        "    <stateVariable sendEvents=\"yes\">\n"
        "      <name>CurrentConnectionIDs</name>\n"
        "      <dataType>string</dataType>\n"
        "      <defaultValue>0</defaultValue>\n"
        "    </stateVariable>\n"
        "  </serviceStateTable>\n"
        "</scpd>\n"
        "";
    return out.print(msg);
  }
};

}  // namespace tiny_dlna
