// Handles media URIs, play/pause/stop, seek, etc.

const char transport_xml[] =
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\
  <scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\
    <specVersion>\
      <major>1</major>\
      <minor>0</minor>\
    </specVersion>\
    <actionList>\
      <action>\
        <name>SetAVTransportURI</name>\
        <argumentList>\
          <argument>\
            <name>InstanceID</name>\
            <direction>in</direction>\
            <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\
          </argument>\
          <argument>\
            <name>CurrentURI</name>\
            <direction>in</direction>\
            <relatedStateVariable>AVTransportURI</relatedStateVariable>\
          </argument>\
          <argument>\
            <name>CurrentURIMetaData</name>\
            <direction>in</direction>\
            <relatedStateVariable>AVTransportURIMetaData</relatedStateVariable>\
          </argument>\
        </argumentList>\
      </action>\
      <action>\
        <name>Play</name>\
        <argumentList>\
          <argument>\
            <name>InstanceID</name>\
            <direction>in</direction>\
            <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\
          </argument>\
          <argument>\
            <name>Speed</name>\
            <direction>in</direction>\
            <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>\
          </argument>\
        </argumentList>\
      </action>\
      <action>\
        <name>Pause</name>\
        <argumentList>\
          <argument>\
            <name>InstanceID</name>\
            <direction>in</direction>\
            <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\
          </argument>\
        </argumentList>\
      </action>\
      <action>\
        <name>Stop</name>\
        <argumentList>\
          <argument>\
            <name>InstanceID</name>\
            <direction>in</direction>\
            <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\
          </argument>\
        </argumentList>\
      </action>\
      <action>\
        <name>GetTransportInfo</name>\
        <argumentList>\
          <argument>\
            <name>InstanceID</name>\
            <direction>in</direction>\
            <relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable>\
          </argument>\
          <argument>\
            <name>CurrentTransportState</name>\
            <direction>out</direction>\
            <relatedStateVariable>TransportState</relatedStateVariable>\
          </argument>\
          <argument>\
            <name>CurrentTransportStatus</name>\
            <direction>out</direction>\
            <relatedStateVariable>TransportStatus</relatedStateVariable>\
          </argument>\
          <argument>\
            <name>CurrentSpeed</name>\
            <direction>out</direction>\
            <relatedStateVariable>TransportPlaySpeed</relatedStateVariable>\
          </argument>\
        </argumentList>\
      </action>\
    </actionList>\
    <serviceStateTable>\
      <stateVariable sendEvents=\"no\">\
        <name>AVTransportURI</name>\
        <dataType>string</dataType>\
      </stateVariable>\
      <stateVariable sendEvents=\"no\">\
        <name>AVTransportURIMetaData</name>\
        <dataType>string</dataType>\
      </stateVariable>\
      <stateVariable sendEvents=\"no\">\
        <name>TransportPlaySpeed</name>\
        <dataType>string</dataType>\
        <allowedValueList>\
          <allowedValue>1</allowedValue>\
        </allowedValueList>\
      </stateVariable>\
      <stateVariable sendEvents=\"no\">\
        <name>TransportState</name>\
        <dataType>string</dataType>\
        <allowedValueList>\
          <allowedValue>STOPPED</allowedValue>\
          <allowedValue>PAUSED_PLAYBACK</allowedValue>\
          <allowedValue>PLAYING</allowedValue>\
          <allowedValue>TRANSITIONING</allowedValue>\
          <allowedValue>NO_MEDIA_PRESENT</allowedValue>\
        </allowedValueList>\
      </stateVariable>\
      <stateVariable sendEvents=\"no\">\
        <name>TransportStatus</name>\
        <dataType>string</dataType>\
        <allowedValueList>\
          <allowedValue>OK</allowedValue>\
          <allowedValue>ERROR_OCCURRED</allowedValue>\
        </allowedValueList>\
      </stateVariable>\
      <stateVariable sendEvents=\"no\">\
        <name>A_ARG_TYPE_InstanceID</name>\
        <dataType>ui4</dataType>\
      </stateVariable>\
    </serviceStateTable>\
  </scpd>";
